name: Build Plugin JAR

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kodu
        uses: actions/checkout@v4

      - name: Konfiguracja Javy 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Nadanie praw wykonywania dla Gradle Wrapper
        run: |
          if [ ! -f gradlew ]; then
            gradle wrapper
          fi
          chmod +x gradlew

      - name: Budowanie pliku JAR
        run: ./gradlew reobfJar

      - name: Udostępnienie gotowego pliku .jar (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: CustomTPA-Plugin
          path: build/libs/CustomTPA.jar
